### ISSUE TITLE
ChangeLog is missing entries for 3.6.2 and 3.6.3

### ISSUE THREAD

**Issue by rillig** [Automattic/Co-Authors-Plus#1071]
https://wordpress.org/plugins/co-authors-plus/ says that the current version is 3.6.3, but inside /wp-admin/, showing the plugin details links to https://github.com/Automattic/Co-Authors-Plus/blob/master/CHANGELOG.md for the ChangeLog, which is missing the entries for 3.6.2 and 3.6.3.

**Comment by chuckreynolds** [comment]
same. PR => https://github.com/Automattic/Co-Authors-Plus/pull/1072

**Comment by chuckreynolds** [comment]
Update... seems the `develop` branch is the current 'main' branch and the plugin repo should link to it instead of master branch as it does currently. 
- [Reference comments in my PR here](https://github.com/Automattic/Co-Authors-Plus/pull/1072#issuecomment-2450866050)
- [Develop branch Changelog](https://github.com/Automattic/Co-Authors-Plus/blob/develop/CHANGELOG.md)

**Comment by chuckreynolds** [comment]
Changed in PR here https://github.com/Automattic/Co-Authors-Plus/pull/1073

**Comment by GaryJones** [comment]
Apologies - looks like `develop` was not merged into `main` upon the last two patch releases. We'll get that addressed.
