### ISSUE TITLE
Pipe character in user meta prevents adding as coauthor

### ISSUE THREAD

**Issue by aheckler** [Automattic/Co-Authors-Plus#370]
If I, for example, have a guest author with `Adam Heckler | One Cool Dude` as the display name, I cannot add that user as a coauthor from within the post editing screen.

I think the bug is here:

https://github.com/Automattic/Co-Authors-Plus/blob/3.2/js/co-authors-plus.js#L195

... where we get the author info using `.split( '|' )`.

We should probably sanitize it or reject pipes in user meta altogether.

From VIP ticket 55563. cc @ryanmarkel

**Comment by mjangda** [comment]
There's a PR with a suggested fix in #361. Better long-term fix though is to move to a not-so-crappy auto-complete library. I think @rcoll was working on this?

**Comment by paulschreiber** [comment]
Updating to select2 4.x should help. See #389.

**Comment by claudiulodro** [comment]
On a similar note but in 2021, a pipe character in the author name causes a broken profile image when adding a guest author:

<img width="633" alt="Screen Shot 2021-03-11 at 11 54 25 AM" src="https://user-images.githubusercontent.com/7317227/110846395-939ddd80-8260-11eb-9f75-a1ff3cfe02a5.png">

This is because exploding e.g. `1234 | user-slug | Adam Heckler | One Cool Dude |  | adam-heckler | example.com/wp-content/uploads/user-avatar.png` on `|` causes  the user slug to be in the index of the user profile picture, so it results in `img src="adam-heckler"`.

Now that it's 2021, can this maybe use JSON or something, or are there backwards-compatibility reasons the ajax call is still inventing its own data format?

**Comment by paulschreiber** [comment]
+100 to using JSON here.
