### ISSUE TITLE
Co-Author Order Not Retained in WordPress 4.8.2

### ISSUE THREAD

**Issue by xcentric-solutions** [Automattic/Co-Authors-Plus#455]
Thanks for this very helpful plugin!

According to the plugin git repo, the latest plugin version 3.2.2 is supposed to include a fix for the Author Ordering issue in WP 4.7+. 

However, we updated to WP 4.8.2 and installed the plugin today .. and we are seeing the ordering issue.

Replicate the issue:
1. Create a multiple author post in WP 4.8.2
2. Change Author order in either the post editor or quick edit views then update post to save changes;
3. Observe that the Author order reverts back to author id after saving the change(s).

Any suggestions on how to correct?

Thanks!

**Comment by rebeccahum** [comment]
I can't say I am experiencing the same issue on CAP 3.2.2 and WP 4.8.2.  Would love to hear if anyone else is though!

**Comment by rebeccahum** [comment]
I can't say I am experiencing the same issue on CAP 3.2.2 + WP 4.8.2. Would love to hear if anyone else is though!

**Comment by xcentric-solutions** [comment]
Hi Rebecca, I've recorded a screencast demonstrating the issue. It can be seen here: 

https://cl.ly/0s05230F3Q2M

There are no browser errors or warnings.

Any ideas why the ordering is not being saved?

**Comment by msubotic** [comment]
Hi @rebeccahum , i'm experiencing the same issue with WP 4.8.2 and CAP 3.2.2 as @xcentric-solutions, any help would be appreciated!

**Comment by mispy** [comment]
I've run into this issue as well. Turns out it was not the fault of the CAP plugin but rather a conflict between it and the Category Order and Taxonomy Terms Order plugin: https://en-au.wordpress.org/plugins/taxonomy-terms-order/

The category ordering plugin appears to override the default behavior of wp_get_post_terms such that it queries wp_terms.term_order (a new field added by that plugin) instead of wp_term_relationships.term_order, giving the wrong order.

**Comment by philipjohn** [comment]
@xcentric-solutions @msubotic Are you also using the plugin @mispy mentions?

**Comment by msubotic** [comment]
Indeed I am. Thanks @mispy for sharing your findings!

**Comment by rebeccahum** [comment]
Thanks to @mispy, we can go ahead and close this issue out!
