### ISSUE TITLE
Function return author login name instead of display name

### ISSUE THREAD

**Issue by ptrckvzn** [Automattic/Co-Authors-Plus#469]
Hello,

The function `coauthors_links` return the login-name (slug) instead of the display name. By looking at the source, I noted that the callback `coauthors_links_single` will return nothing when no website is set for a guest author. The two conditionals seems to be the problem.

https://github.com/Automattic/Co-Authors-Plus/blob/b2bc1d3000fdb9b2de83601ccd26d14c9e023bf8/template-tags.php#L381

The conditional should check at the same time if the author type is guest-author _and_ if the author meta website is set.

```
if ( 'guest-author' === $author->type && get_the_author_meta( 'website' )) {
		return sprintf( '<a href="%s" title="%s" rel="external" target="_blank">%s</a>',
			esc_url( get_the_author_meta( 'website' ) ),
			esc_attr( sprintf( __( 'Visit %s&#8217;s website' ), esc_html( get_the_author() ) ) ),
			esc_html( get_the_author() )
		);
}
```

If no website is set, the function returns nothing and coauthors__echo returns the login-name.

https://github.com/Automattic/Co-Authors-Plus/blob/master/template-tags.php#L187

I'd be happy to submit a PR.

**Comment by philipjohn** [comment]
> I'd be happy to submit a PR.

That'd be great!

Could you also add a little more detail please? How does this affect the front end, and in what ways? Can you lay out some steps to reproduce so we can see this problem in action for ourselves?

**Comment by binodkalathil** [comment]
Hi @philipjohn,

This is unexpected output of the template tag `coauthors_links` added by the plugin. The template tag is expected to output co-authors display names with links to their websites if they've provided them. If no website is provided in the guest author profile then the expected output is just the guest authors display names.

Here if a guest author have not provided a website then the template tag outputs the username of the author instead of display name.

Steps to reproduce:
1. Add template tag `coauthors_links` in the theme
2. Add a guest author( Admin > Users > Guest Authors ) without a website and add the author to one of the posts
3. Check the co-authors list of the post view in front end. It will show the user name instead of the display name of the guest author we just created.

I will create a PR for this
