### ISSUE TITLE
Deleting user A, replacing them with user B results in two authors attached to post

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/Co-Authors-Plus#572]
### Scenario ###
You are _not_ on WordPress.com (or another multisite instance).

You have several WordPress user accounts: B, C, D, …
You have several CoAuthors Plus profile b, c, d, …

Each WordPress user is mapped to a corresponding CoAuthors Plus Profile.

User B (with profile b) writes many articles: A[1], A[2], … A[N]. User B is the sole author for these articles.

User B leaves the organization.
User B's account is removed:

    <hostname>/wp-admin/users.php?action=delete&user=63&_wpnonce=<nonce>

The following prompt appears:
![pasted_image_7_19_18__3_34_pm](https://user-images.githubusercontent.com/86784/42965887-541eac84-8b69-11e8-923d-01f3b00d0eb4.png)

"Attribute all content to <user Q>" is chosen and Confirm Delete is pressed.

### Actual Result ###
Articles A[1], A[2], … A[N] have both User B and and User Q as authors.

### Expected Result ###
Articles A[1], A[2], … A[N] have only User B as author.

**Comment by anigeluk** [comment]
Should that expected result be user Q rather than user B as user B's account has been removed.

**Comment by paulschreiber** [comment]
No. Because profile b was always the only author, and profile b has not been remove.

**Comment by psaikali** [comment]
Hey @paulschreiber! I tried to replicate your bug but could only get expected behavior. 

FAQ states:
> When a user is deleted from WordPress, they will be removed from all posts for which they are co-authors. If you chose to reassign their posts to another user, **that user will be set as the coauthor instead**.

During my tests, if I deleted user B and attribute all content to user Q, user B posts get assigned to user Q as expected. The Guest Author associated to the Deleted User is deleted too (that makes sense IMHO and was fixed in #120).

> **Actual Result:** Articles A[1], A[2], … A[N] have both User B and and User Q as authors.

Unfortunately, I could not recreate this bug. Could you try to replicate this behavior again and:
1. let me know if you still have User B and User Q assigned to the posts, even after deleting User B?
2. confirm that the posts where only assigned to User B before deleting the user?
3. confirm that you are using the plugin code from the latest `master` branch?

If you still get the Users B & Q as authors after User B deletion, that's definitely a bug. If so, could you let me know in which order you did the following steps:
1. creating the Guest Author
2. creating the User B <> Guest Author relationship
3. publishing the posts
4. (maybe manually assigning User B/Guest Author to the posts, if it was not the default author)

Thanks for your help!

**Comment by WPprodigy** [comment]
I've tested this pretty thoroughly and am also having trouble replicating.

Both when deleting the WP user and the Guest Author, the posts are correctly re-assigned for me. So I'm thinking this has perhaps been resolved with another fix at some point?

Closing for now.
