### ISSUE TITLE
Docs on wp.org plugin listing have outdated screenshots

### ISSUE THREAD

**Issue by benlk** [Automattic/Co-Authors-Plus#627]
Compare https://vip.wordpress.com/plugins/co-authors-plus/ to https://wordpress.org/plugins/co-authors-plus/, and observe that the .org plugin listing has some very outdated screenshots.

- [ ] replace screenshot-1.png, screenshot-2.png, screenshot-3.png in this repo with newer screenshots

**Comment by kodemonster** [comment]
@benlk  yeh agreed they are out dated, would it be alright if I can work on this and make a PR?

**Comment by benlk** [comment]
I assume so, but I'm not an owner of this repository.

**Comment by nielslange** [comment]
> Compare https://vip.wordpress.com/plugins/co-authors-plus/ to https://wordpress.org/plugins/co-authors-plus/, and observe that the .org plugin listing has some very outdated screenshots.

@benlk Thanks for pointing this out.

> @benlk yeh agreed they are out dated, would it be alright if I can work on this and make a PR?

@kodemonster PRs are always welcome. Would you still be interested in spinning up a PR for this issue?

**Comment by gamebits** [comment]
The docs link in this issue was eventually migrated to

https://docs.wpvip.com/how-tos/add-guest-bylines-to-your-content-with-co-authors-plus/

before ultimately being redirected to the wporg plugin repository.

Here are some Wayback Machine captures:

https://web.archive.org/web/20170712073056/https://vip.wordpress.com/plugins/co-authors-plus/

https://web.archive.org/web/20220929134731/https://docs.wpvip.com/how-tos/add-guest-bylines-to-your-content-with-co-authors-plus/

**Comment by benlk** [comment]
So the issue remains: the wp.org screenshots are very outdated.

**Comment by gamebits** [comment]
Correct. So are the ones in the Wayback Machine, though.
