### ISSUE TITLE
Can't re-order authors

### ISSUE THREAD

**Issue by Intrinsic29** [Automattic/Co-Authors-Plus#735]
Good afternoon,

I am unable to re-order authors. I can drag the authors to the order I want them in, but then when I update it, they remain in alphabetical order. This has worked in the past so I'm guessing a WP update is messing it up.

Thanks!

**Comment by rebeccahum** [comment]
@Intrinsic29 Can you please provide some steps to reproduce this, along with the current version of WP and Co-Authors-Plus.

**Comment by Intrinsic29** [comment]
Hi,

Current version of WP is 5.4.1 and Co-Authors-Plus is 3.4.3. 

I have two authors, each with a first and last name. When I try to drag them so the main author is first then click update, it still shows them in alphabetical order.

Thanks!

**Comment by TheCrowned** [comment]
I can say on WP 5.5.1 and latest master CAP I don't see the issue. I am able to reorder authors and, upon save, they stay where they should. I have tried both with and without Gutenberg (i.e. with Classic editor plugin). Maybe there is something else at stake? Can you try with `master`, instead of the public release from WP.org? Have you tried with all other plugins off?

**Comment by nielslange** [comment]
Closing this issue as it does no longer seem to appear and the reported hasn't replied yet.
