### ISSUE TITLE
Adding Gutenberg input to the guest author post type

### ISSUE THREAD

**Issue by ckeeney** [Automattic/Co-Authors-Plus#745]
I'd like to add Gutenberg editor on the Guest Author post type.  I added the following hook, without success.  I believe this code does not work because the 'editor' support is explicitly removed after `register_post_type` is called, and my hook runs during execution of that function.

Is there a reason editor (and title) support is explicitly removed after the post type is registered?

https://github.com/Automattic/Co-Authors-Plus/blob/221e4df88d65b1ba2eb4467d16e4ba74d82f37c9/php/class-coauthors-guest-authors.php#L134-L141

```php
function modify_guestauthor_posttype_args( $args, $post_type ) {
    if ( $post_type !== "guest-author" ) {
        return $args;
    }
    $args['show_in_menu'] = true;
    $args['show_in_rest'] = true;
    $args['has_archive'] = true;
    $args['supports'][] = 'editor';

    return $args;
}
add_filter( 'register_post_type_args', 'modify_guestauthor_posttype_args', 20, 2 );
```

**Comment by TheCrowned** [comment]
I guess the reason might be trying to mimic as closely as possible the regular `Users` behaviour, which don't have `title` nor `editor`. Why would you want to add title and editor, though? That said, the post type is already _not_ specifying `title, editor` in the `supports` field of the post type, so it is already taking them away this way. I guess if one puts them explicitly back, it should be allowed :)

**Comment by ckeeney** [comment]
I don't care much about adding a title, I only mentioned it because I saw it is also explicitly removed after the hooks run.

Right now Guest Author has a bio field that is just plain text.  At a minimum, my bios require italics and bold formatting.  I could add a WP 4 legacy editor input as a custom field, but I would prefer to have the gutenberg editor for bios.  My authors are already familiar with that editor.

**Comment by nielslange** [comment]
Hello @ckeeney, I'm afraid adding Gutenberg to the guest authors pages to manage their bio will not work. Gutenberg behaves different from the classic editor. Adding Gutenberg, would show the editor on top and all other fields such as display name, first name, last name, email, etc. below the editor. This would lead to a confusing flow. 

In theory, it would be possible to implement the current the guest author page using [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/). The guest author page could then look like this:

![add-new-guest-author](https://user-images.githubusercontent.com/3323310/112837782-8426ed00-90c6-11eb-9f89-185417e1b259.png)

However, this would mean that all users who have extended the guest author page would no longer see their extended form and would have to implement the desired fields again using [Advanced Custom Fields](https://wordpress.org/plugins/advanced-custom-fields/). 

Due to backwards compatibility, I'd rather vote against such as change, but I'm happy to keep this issue open so that others can share their thoughts in this case.

**Comment by rebeccahum** [comment]
> Is there a reason editor (and title) support is explicitly removed after the post type is registered?

It is explicitly removed because we want the guest authors to behave more like WP_Users (which do not seem to have Gutenberg in the "Biographical Info".

**Comment by nielslange** [comment]
Closing this issue based on https://github.com/Automattic/Co-Authors-Plus/issues/745#issuecomment-809422163.
