### ISSUE TITLE
Author autocomplete silently fails on posts with no author

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/Co-Authors-Plus#799]
In the latest release, [there is a check for `empty( $_REQUEST['existing_authors'] )` in the ajax author autocomplete](https://github.com/Automattic/Co-Authors-Plus/blob/614dc28d47c8c3e86bd093a69c3e47d3eb1216f6/co-authors-plus.php#L1200), and it silently exits if there are no authors. This change was introduced in [this PR](https://github.com/Automattic/Co-Authors-Plus/commit/c51143e9d332d3818e4641c5dd6de79fd314a308), and I'm not sure the purpose, since it's not really a phpcs-related change.

If a post gets into a state where it has no author and the ajax autocomplete always fails, it will not be possible to ever assign an author to the post using Co-Authors Plus.

To reproduce:
1. Set up a post so that it has no author. (manually edit the DB, etc.)
2. On the post, try and type in an author on the CAP author autocomplete box. Observe no autocomplete happens. If you examine the network response, the response is empty.
3. You cannot assign an author to the post because the autocomplete always fails.

<img width="1671" alt="Screen Shot 2021-06-01 at 1 50 29 PM" src="https://user-images.githubusercontent.com/7317227/120389113-d6f86d00-c2e0-11eb-9bd7-d424140418df.png">

**Comment by rebeccahum** [comment]
@nielslange Can you please take a look at this?

**Comment by nielslange** [comment]
I'm on it, @rebeccahum.

**Comment by nielslange** [comment]
@claudiulodro Can you tell me how to reproduce this case? When removing the author from a post on my end, I then see the admin account as fallback author listed.

I wonder how a post of page can lose its author without modifying the database. Reverting the change that caused this  issue, is no problem. That said, I'd love to understand how this can become an issue as I assumed that it's not possible of having a page or post without an author, unless the author will be manually removed from the database. If that's that only case in which this can become a problem, I wonder if the plugin should take such a case into consideration. 

In https://github.com/Automattic/Co-Authors-Plus/pull/784, I added `|| empty( $_REQUEST['existing_authors'] )` to ensure that `$_REQUEST['existing_authors']` exists before it is used in https://github.com/Automattic/Co-Authors-Plus/blob/614dc28d47c8c3e86bd093a69c3e47d3eb1216f6/co-authors-plus.php#L1205. That's why this part had been added initially.

**Comment by claudiulodro** [comment]
Apologies @nielslange, my test instructions weren't quite accurate! :)

1. Assign a guest author to a post.
2. Delete the guest author and select "leave unnasigned"

<img width="974" alt="Screen Shot 2021-06-03 at 10 07 30 AM" src="https://user-images.githubusercontent.com/7317227/120684584-b7358600-c453-11eb-8cb9-74a5f6c87ea2.png">

Then you should encounter the issue.

**Comment by nielslange** [comment]
Thanks for the further testing instructions, @claudiulodro. When trying to reproduce this case on my end, the admin account automatically gets assigned as soon as I delete the guest account. I assume that's because I created the test post using the admin account initially. As the guest author account is a CPT, I'm unable to log into that account directly to create that test post using the guest author account.

Would you be able to create a quick video on how you run the complete test case on your end?

**Comment by rebeccahum** [comment]
@nielslange Thanks for looking into this. Since it is a change from a PR that should not affect functionality, can you make a PR to revert the change while this is being investigated?

**Comment by nielslange** [comment]
> @nielslange Thanks for looking into this. Since it is a change from a PR that should not affect functionality, can you make a PR to revert the change while this is being investigated?

Sure. No problem, @rebeccahum. I was simply trying to understand how this case can be reproduced, as I'm unable to reproduce it so far. That said, a fix is on the way.
