### ISSUE TITLE
Contributor cannot see backend post listing for authors

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/Co-Authors-Plus#820]
Reproduction steps: 
1) Create some posts from admin account "admin"
2) Log out and now log in with a different user account that has the role "Contributor"
3) Go to http://one.wordpress.test/wp-admin/edit.php?post_type=post&all_posts=1 and you should see a whack of post listings
4) Click on "admin" in the post view: http://one.wordpress.test/wp-admin/edit.php?author_name=admin
5) You will see "No found posts" which is incorrect

Probably related to this set of lines: https://github.com/Automattic/Co-Authors-Plus/blob/ce7c26ed5cb6a384557fcde07a4bb7b34b482bd3/co-authors-plus.php#L739-L744

**Comment by lschuyler** [comment]
I can replicate this, but only if the contributor has 1 or more posts of their own, and the admin user doesn't have a linked guest author.

The trouble first seemed to be the `preg_replace` in line 743, as you suspected above. My first hunch was easiest fix would be to change the `$id` to the id of the `author_name` in the URL, but this change creates more trouble and causes 3 of the PHPUnit tests fail. 

Next I tried a more generic `preg_replace` in 743 that only looks for a numeric value (of any value). But this still doesn't result in an accurate query.

Looking closer at the main_query that is used when requesting all the posts of the admin user (`/wp-admin/edit.php?author_name=admin`), I noticed this query is quite different when logged into the contributor's account compared to the administrator's account. 

When logged into the contributor's account, the query contains the author IN condition: `AND ( wp_posts.post_author IN (12)` , with that 12 representing the id of the contributor account I'm logged into. Really these queries should be the same, so why does the query attempt to get the posts for the admin user and the contributor account I'm logged in to? The account that we are logged into should be irrelevant to this particular query. There is no need to grab the posts of the specified `author_name` AND the posts of the contributor account we are logged into.

### Core bug?

With some further bug tracing with @mikeyarce, we discovered this behavior can be replicated with the same scenario, even when the CAP plugin is disabled!

Taking a look at core, there seems to be an issue where the query is built in `/wp-includes/class-wp-query.php`, although this is only obvious when the `author_name` is specified as a parameters in the URL. Usually, outside of CAP, the URL for this request would not be using the `author_name`, but rather the id, in this format: `/wp-admin/edit.php?post_type=post&author=1`, but `class-wp-query.php` will handle the `author_name` parameter.

Adding a `&& ! is_admin()` [to this line](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php#L2243 ) fixes when `author_name` is specified in the URL (with or without CAP), but if you disable CAP and test a default link instead, `wp-admin/edit.php?post_type=post&author=1` it returns all the posts, rather than just the posts by the specified admin author, which isn't right either.

Rather than chasing a possible core bug that only occurs with the `author_name` in the URL (which may only be used by CAP?), to fix this in CAP we need to intervene when the `post.author IN` notation is returned from WordPress, and replace it with an `=` notation instead of `IN`. Since this issue only causes problems on the posts admin page, so I've proposed a fix that adds an additional if/else statement to target this narrow circumstance, and adjusts the query.

PR: https://github.com/Automattic/Co-Authors-Plus/pull/823
