### ISSUE TITLE
Show a warning message when creating a guest author from a user

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Co-Authors-Plus#94]
When creating a guest author from an existing user, it would be wise to show a warning (to avoid any mistaken clicks).

http://wordpress.org/support/topic/guest-author-term_id-mistaken-for-user-id-in-get_coauthors?replies=3#post-3534623

**Comment by rebeccahum** [comment]
Is this issue still relevant? If I am understanding things correctly, it seems like the wording and plugin screen design/flow has changed since the issue has been opened.  I am no longer seeing a feature to create a Guest Author from an existing User in the UI.  I know this feature exists in the WP CLI command `create-guest-authors`, but I don't think the author from WP.org was referring to that.  Also, when you go to "Add New" on the Guest Authors under the Manage Users section, the submit button is "Add New Guest Author", so it shouldn't be confusing for the user if they are creating a guest author or a regular user.
cc: @philipjohn

**Comment by rebeccahum** [comment]
Is this issue still relevant? If I am understanding things correctly, it seems like the wording and plugin screen design/flow has changed since the issue has been opened.  I am no longer seeing a feature to create a Guest Author from an existing User in the UI.  I know this feature exists in the WP CLI command `create-guest-authors`, but I don't think the author from WP.org was referring to that.  Also, when you go to "Add New" on the Guest Authors under the Manage Users section, the submit button is "Add New Guest Author", so it shouldn't be confusing for the user if they are creating a guest author or a regular user.
cc: @philipjohn

**Comment by philipjohn** [comment]
Yep, good spot, this doesn't seem relevant anymore.
